export const loreContent = {
  collapse: {
    heading: 'Humanity After Collapse',
    lead: 'The sky did not fall all at once. It thinned.',
    sections: [
      {
        heading: 'The Unraveling',
        text: 'Between 2035 and 2055, atmospheric destabilization escalated from crisis to permanence. Coastlines shifted inward. Agricultural systems failed in cascading waves. Supply chains collapsed not in a single dramatic event, but in a slow erosion that normalized emergency governance across every continent. Aquifers drained beneath cities that had existed for centuries. Monsoon patterns shifted until entire agricultural regions produced nothing. Coastal megacities lost districts to saltwater incursion one neighborhood at a time. By 2058, the first multi-coastal displacement crisis marked the end of recovery politics. There would be no return to the old world.',
      },
      {
        heading: 'The Scale of Loss',
        text: 'Inland displacement accelerated as coastlines retreated. Northward migration pressure overwhelmed infrastructure corridors. Conflict was less ideology than access to breathable air and reliable power. "Safe corridors" formed around stable energy and water sources, and these corridors became the skeleton of what would eventually become the Haven Network. The collapse was not a single catastrophe. It was a thousand small failures compounding across decades, and by the time anyone had the language to describe what was happening, the world that language was built to describe had already changed.',
      },
      {
        heading: 'Reorganization',
        text: 'What followed was not extinction. It was reorganization on a scale no previous civilization had attempted. Humanity did not retreat into caves. It built new skies. In 2063, the Sahara Core prototype ignited, establishing a continental-scale fusion backbone that would become the new energy geography. Two years later, Haven One broke ground. A generation of engineers, biologists, and systems architects constructed sealed biodome cities capable of maintaining breathable air, stable climate, and civil order independent of the planet\'s failing atmosphere. Each Haven was sited on stable bedrock near existing infrastructure corridors, its specialization distributed to avoid single-point failure.',
      },
      {
        heading: 'The Survival Infrastructure',
        text: 'By 2094, twelve Earth Havens stood as the surviving infrastructure of human civilization. Each one a closed biosphere, powered by the Sahara Core fusion backbone, connected through the Traverse transit network, and governed by a fragile cooperative charter ratified in 2110. The species that once took open skies for granted now lived beneath engineered membranes, watching simulated sunsets calibrated by atmospheric technicians. The Havens were not merely shelters. They were proof that a species capable of breaking its own world was also capable of building a new one.',
      },
      {
        heading: 'The Resilience of the Species',
        text: 'What defines this era is not the collapse. It is what came after. Within three decades, humanity transitioned from planetary dependence to engineered independence. Children born inside the domes learned atmospheric chemistry before geography. Engineers maintained artificial weather systems as a public utility. Artists painted skies they had never seen from memory passed down by their grandparents. The species adapted not by returning to what was lost, but by building something that had never existed before: a civilization that manufactured its own sky, its own seasons, its own horizon.',
      },
      {
        heading: 'Last Local Light',
        text: 'Older generations still remember what was lost. Real sunsets. Unscheduled weather. Coastlines that stayed where they were. The assumption that nature was background, not a system that could be broken. They call the memory "Last Local Light," and it carries the weight of a world that no longer exists. In the cultural archives, Last Local Light has become a formal ceremony — a moment of collective remembrance for the final natural sunset recorded before the domes sealed. People pause when a simulated sunset looks too perfect. Older citizens remember storms not as spectacle but as normal. The domes are not a concept. They are a grief response turned into infrastructure.',
      },
    ],
  },

  network: {
    heading: 'The Haven Network',
    lead: 'Fourteen biospheres. One fragile civilization.',
    intro: 'The Haven Network is the surviving infrastructure of human civilization: twelve sealed biodome cities on Earth, one lunar research station, and one Martian agricultural outpost. Each Haven specializes in a critical civilizational function, from energy distribution to atmospheric simulation to cultural memory. Together they form a distributed civilization connected through trade, research exchange, orbital infrastructure, and the Traverse transit network. No single Haven is self-sufficient. Each depends on the others for resources, knowledge, and the collective will to continue. Specialization creates interdependence. Interdependence creates leverage. The network is humanity\'s greatest engineering achievement, and its most fragile.',
    features: [
      {
        title: 'Membrane Architecture',
        text: 'Every Haven operates beneath a multilayer structural dome that regulates pressure, filters light, and maintains atmospheric composition. The membrane is visible at distance — a curvature that reminds residents they live inside an engineered volume. Simulated sky cycles provide psychological stability. Clouds drift on schedule. Atmospheric smoothing systems make continuous micro-adjustments to air composition, pressure, and circulation. The light feels natural until you remember it is engineered.',
      },
      {
        title: 'Infrastructure Hum',
        text: 'Life inside a Haven has a baseline frequency. Air recycling currents. Transit vibration beneath the floor. Cooling systems cycling in the technical tiers. A constant, invisible companion that people stop noticing until it changes. When it changes, everyone notices. Each Haven\'s hum has a slightly different character, shaped by its primary systems. Residents who travel between Havens often remark that the first thing they notice is not the architecture, but the pitch.',
      },
      {
        title: 'Trade and Research Exchange',
        text: 'No Haven operates in isolation. Agricultural yields from Haven Three feed populations across the network. Energy allocations from Haven Ten power every membrane and atmospheric processor. Materials from Haven Eleven become the structural components of expansion projects. Research data flows through Coalition channels in standardized formats, peer-reviewed across multiple Havens before implementation. The Traverse network carries cargo alongside passengers, moving critical supplies on schedules measured in hours.',
      },
      {
        title: 'Public Metrics',
        text: 'Every Haven displays real-time system data on public boards: membrane integrity, air recycle efficiency, cloud layer stability, Traverse delays. The numbers translate fear into something measurable. Citizens read them the way previous generations checked the weather. They provide the illusion of control. When the numbers change, conversations shift. When the numbers spike, the cost is felt in small ways first — thinner air, longer transit queues, dimmer corridors in outer ring districts.',
      },
      {
        title: 'Orbital Infrastructure',
        text: 'Above the membranes, a network of orbital platforms supports communication relays, solar collection arrays, and deep-space observation equipment. The orbital layer connects the Earth Havens to Selene and Ares Reach, maintaining the data and energy links that make the off-world settlements possible. Orbital maintenance crews train at Haven Nine and deploy on rotating schedules — one of the most dangerous and essential roles in the network.',
      },
      {
        title: 'Tiered Access',
        text: 'Haven infrastructure operates on clearance levels: public, maintenance, administrative, and classified. Most civilians experience only the public tier — the simulated sky, the residential corridors, the public metrics boards. The maintenance corridors, administrative spines, and classified research levels form a parallel architecture that most residents will never see. The tiers exist because the margin between survival and failure is thinner than the public metrics suggest.',
      },
    ],
  },

  havens: [
    {
      id: 'H-01',
      name: 'Haven One',
      location: 'Western Europe',
      population: '~620,000',
      specialization: 'Governance and Coalition Administration',
      function: 'Coalition charter operations, policy enforcement, inter-Haven arbitration.',
      visual: 'Polished civic plazas, administrative towers, secure comm spines. Architecture designed to communicate permanence and institutional authority. Wide corridors converge on civic chambers where delegates from all fourteen biospheres convene.',
      culture: 'Protocol-first. People speak in implications. Authority is ambient, woven into architecture and procedure. Social mobility is measured in access levels. Children grow up learning procedural language before they learn to argue.',
      environment: 'The air feels precise. Corridors are wide and calibrated for controlled foot traffic. Public spaces are designed for visibility. Every surface communicates order. Filtered light runs on a slightly cooler spectrum than most Havens, giving the dome an air of perpetual clarity.',
    },
    {
      id: 'H-02',
      name: 'Haven Two',
      location: 'Central Europe',
      population: '~480,000',
      specialization: 'Energy Grid Stabilization',
      function: 'Allocation math, load balancing, grid forecasting, crisis reroutes.',
      visual: 'Transmission corridors, humming substations, status walls displaying real-time power distribution across the network. The architecture is functional, built around conduit access and monitoring infrastructure.',
      culture: 'Utility ethics. Morality translated into megawatts. The people here understand that energy allocation is the real constitution of the Haven Network. There is a quiet pride in knowing that every other Haven depends on the numbers they manage.',
      environment: 'The hum is louder here than in any other Haven. Substations pulse with visible rhythm. Status boards cycle constantly. The air carries a faint warmth from conduit proximity. At night, when the simulated sky dims, the glow of relay indicators becomes the dominant light source.',
    },
    {
      id: 'H-03',
      name: 'Haven Three',
      location: 'East Africa',
      population: '~710,000',
      specialization: 'Biological Sciences and Agriculture',
      function: 'Food systems, bioengineering, ecological stability, medical staples.',
      visual: 'Vertical farms, humidity-managed green corridors, lab glass beside soil. Tiered growing chambers rise through the dome\'s interior, their translucent walls glowing with photosynthetic light.',
      culture: 'Patient, life-centered pragmatism. The people here grow things. They understand cycles, patience, and the difference between control and cultivation. Meals in Haven Three carry a weight they do not carry elsewhere — the understanding that food is not a commodity but an engineered miracle.',
      environment: 'The air is thicker here, richer. Humidity hangs in the corridors between growing tiers. Light is tuned for photosynthesis first, human comfort second. Green dominates every sightline. The scent of living soil — engineered, but alive — is the signature of this Haven.',
    },
    {
      id: 'H-04',
      name: 'Haven Four',
      location: 'East Asia',
      population: '~530,000',
      specialization: 'Advanced Mathematics and Fold Modeling',
      function: 'Deep Fold simulation, corridor geometry, classified research.',
      visual: 'Minimalist interiors, projection wells, compute tiers stacked in quiet verticals. Surfaces chosen for low visual noise. Projection wells cast geometric visualizations into open chambers where research teams observe simulated Fold geometries in three dimensions.',
      culture: 'Model-first confidence built on curated certainty. The mathematicians here believe the universe can be predicted. Their models are elegant, precise, and increasingly incomplete. There is a tension between the elegance of their work and the growing evidence that the Fold does not behave as cleanly as their equations suggest.',
      environment: 'Clean lines. Reduced color. Projection wells cast pale geometric light into corridors. The silence here is designed, not accidental. It is a place built for concentration. Sound dampening is woven into the walls. Footsteps barely register.',
    },
    {
      id: 'H-05',
      name: 'Haven Five',
      location: 'Mediterranean Basin',
      population: '~390,000',
      specialization: 'Cultural Archives and Memory Preservation',
      function: 'Civilizational memory, art, governance archives, Last Local Light.',
      visual: 'Museums, archive stacks, ceremonial civic rooms. Spaces that feel older than the dome that contains them. The architecture deliberately references pre-collapse styles — arched corridors, natural stone surfaces, warm lighting that mimics sunlight through glass rather than membrane filtration.',
      culture: 'Tradition-forward, resistant to imposed standardization. Haven Five preserved Last Local Light as a cultural symbol and resisted full Universal Time adoption for months. They believe cultural integrity is survival. The archivists here see themselves as guardians of continuity — the thread connecting what humanity was to what it is becoming.',
      environment: 'Warmer light here than anywhere else in the network. The corridors feel deliberately aged, their surfaces chosen for texture rather than efficiency. Somewhere in the lower archives, the air smells like paper. Display galleries rotate exhibitions that most other Havens will never see in person.',
    },
    {
      id: 'H-06',
      name: 'Haven Six',
      location: 'South Asia',
      population: '~870,000',
      specialization: 'Atmospheric Simulation Technology',
      function: 'Weather projection, air composition smoothing, dome climate control.',
      visual: 'The dome interior is designed to feel open — wide sight lines, graduated ceiling heights, and atmospheric effects that create the convincing illusion of distance and depth. Residential density, atmospheric hubs hidden behind the appearance of comfort.',
      culture: 'Civilian-first. Sensitive to quality-of-life reductions. The people here feel the cost of expansion before anyone else, in thinner air and dimmer corridors during grid strain events. There is an aesthetic sophistication born from living inside the most convincing simulation of the old world.',
      environment: 'The sky here is the best in the network. Cloud formations cycle with artful precision. Simulated breezes carry carefully tuned humidity. It is the most convincing illusion of the old world, which makes the moments it falters all the more disturbing.',
    },
    {
      id: 'H-07',
      name: 'Haven Seven',
      location: 'Southeast Asia',
      population: '~510,000',
      specialization: 'Traverse Infrastructure',
      function: 'Anchor authorization, transit scheduling, corridor maintenance oversight.',
      visual: 'Node maps, anchor control arrays, secure ops floors humming with transit coordination. Massive display walls show the real-time status of every active Traverse corridor, with color-coded indicators for stability, capacity, and scheduled maintenance windows.',
      culture: 'Kingmaker culture. Mobility equals leverage. Haven Seven controls who moves and when. In a civilization where most people rarely leave their dome, transit authorization is power. The culture here is built around access — who has it, who grants it, and what it costs.',
      environment: 'Screens everywhere. Node maps pulse with real-time corridor status. The operational floors vibrate with the constant rhythm of anchor calibration. Movement here is measured in windows and permissions. The architecture feels transitional by design — corridors that widen into departure halls, waiting areas that face arrival gates.',
    },
    {
      id: 'H-08',
      name: 'Haven Eight',
      location: 'Northern Africa',
      population: '~440,000',
      specialization: 'Harmonic Signal Analytics',
      function: 'Signal interpretation, membrane resonance monitoring, anomaly detection.',
      visual: 'Waveform rooms, sensor towers, scaffolds that never fully disappear from the skyline. The dome interior is punctuated by detection arrays rising through residential districts, their scaffolding a permanent part of the architecture.',
      culture: 'Instinct-first culture shaped by loss. A membrane shear incident in 2083 became doctrine here. The people of Haven Eight build procedure from failure. They trust what they can hear. There is a listening discipline unique to this Haven — a patience with ambiguous data that other research cultures lack.',
      environment: 'The sensor arrays are visible from anywhere in the dome, scaffolded towers bristling with detection equipment. Waveform displays line the research corridors. The baseline hum here carries information that trained ears can read.',
    },
    {
      id: 'H-09',
      name: 'Haven Nine',
      location: 'North America',
      population: '~560,000',
      specialization: 'Aerospace and Pilot Training',
      function: 'Crew training, simulation rigs, Fold doctrine, orbital crew deployment.',
      visual: 'Centrifuge halls, zero-g corridors, training theaters that prepare human bodies for environments they were never designed to survive. Cavernous chambers house centrifuge arrays and pressure-variable training environments.',
      culture: 'Competitive calm. Identity tied to readiness. The pilots and crew trained here carry themselves with a particular stillness, as if perpetually waiting for a signal to move. Washout rates are high, and those who complete training carry it as a permanent identity.',
      environment: 'The architecture accommodates motion. Corridors are wider, ceilings higher. Centrifuge housings vibrate at frequencies you feel in your teeth. Simulation theaters project deep black and impossible geometries. The residential districts are deliberately quiet — designed for recovery between training cycles.',
    },
    {
      id: 'H-10',
      name: 'Haven Ten',
      location: 'Saharan Region',
      population: '~350,000',
      specialization: 'Fusion Research / Sahara Core Interface',
      function: 'Sahara Core management, fusion research, economic stability backbone.',
      visual: 'Industrial-scale conduits, controlled access zones, the physical interface between civilization and its power source. Massive conduit arrays run visibly through every district, their scale a constant reminder of what this Haven maintains.',
      culture: 'Output-driven confidence. "We keep the lights on." Haven Ten carries the weight of knowing that every membrane, every atmospheric cycle, every Traverse corridor runs on the energy they manage. The clarity that comes from understanding exactly how important your work is.',
      environment: 'The scale is different here. Conduits run visibly through corridors. Access zones are demarcated by pressure seals and authorization checkpoints. The hum is not background here. It is the primary sound. The ground vibrates with the deep pulse of fusion containment.',
    },
    {
      id: 'H-11',
      name: 'Haven Eleven',
      location: 'South America',
      population: '~420,000',
      specialization: 'Materials Science',
      function: 'Fold components, composite research, structural metallurgy.',
      visual: 'Stress rigs, test chambers, foundry-adjacent labs where new materials are broken to understand how they hold. Thick walls, reinforced corridors, blast-rated test chambers visible from residential walkways.',
      culture: 'Hands-on skepticism. Respects fracture. The researchers here do not trust models until material proves them. They understand that technology scars the things it touches. If you cannot hold it, stress it, and break it, you do not understand it.',
      environment: 'Heat from foundry adjacency warms the research levels. Stress rigs vibrate during testing cycles. The corridors carry the faint metallic taste of composite fabrication. Tools here are heavy, calibrated, and scarred from use.',
    },
    {
      id: 'H-12',
      name: 'Haven Twelve',
      location: 'Oceania',
      population: '~380,000',
      specialization: 'Rapid Structural Response Engineering',
      function: 'Dome integrity, emergency response, maintenance doctrine.',
      visual: 'Workshops, repair teams moving with practiced efficiency, equipment staged for rapid deployment. The dome interior is organized around readiness — staging areas, equipment bays, and rapid-deployment corridors designed for speed rather than comfort.',
      culture: 'Practical stability-first pride. The people here maintain the domes. They brag about uptime metrics. They know the numbers behind every membrane reading because they are the ones who keep those numbers steady. A blue-collar identity that stands apart from the research cultures of other Havens.',
      environment: 'The infrastructure hum is more personal here. Residents recognize its pitch, its rhythm. When it changes, hands tighten on railings. Filtered light casts warm-gold through the dome, convincing enough to forget it is scheduled. The workshops never fully quiet — somewhere, a team is always preparing for the next deployment.',
    },
  ],

  settlements: {
    heading: 'Off-World Settlements',
    lead: 'The first permanent steps of a species leaving its home planet.',
    intro: 'Beyond Earth\'s twelve Havens, humanity has established two off-world biomes: one on the Moon, one on Mars. These are not colonies in the romantic sense. They are research outposts and proving grounds, sustained by the same Sahara Core energy backbone and Traverse network that connects the Earth Havens. They represent something extraordinary: the first generation of humans born knowing that survival no longer requires a single planet.',
    significance: 'The off-world settlements changed the psychological architecture of the species. For the first time since the collapse, humanity was not simply maintaining what it had built. It was reaching. The decision to establish permanent presence beyond Earth was not universally supported — resources allocated to off-world expansion are resources not spent on improving conditions inside the domes. But the settlements exist because a critical mass of people believed that a species confined to one damaged world is a species with an expiration date.',
    locations: [
      {
        name: 'Selene',
        designation: 'H-13',
        body: 'Luna',
        population: '~12,000',
        function: 'Deep space research and resonance detection. A quiet outpost for listening far beyond Earth\'s domes. Selene operates the most sensitive deep-space observation equipment in the Haven Network, free from the electromagnetic interference and atmospheric distortion that limit Earth-based instruments.',
        visual: 'Low-gravity corridors, stark lighting, regolith shielding. Observation arrays pointed into black. The architecture is minimal by necessity — every kilogram of material was transported through the Traverse at significant energy cost. Corridors are narrow. Ceilings are low. The surfaces are raw composite and lunar regolith pressed into structural panels.',
        culture: 'Small teams. High competence. Little patience for politics. The people here chose distance. Silence feels earned. There is an intimacy to Selene that the Earth Havens cannot replicate — everyone knows everyone, and the shared commitment to isolation creates bonds that institutional structures cannot manufacture.',
        identity: 'Humanity\'s ear pressed to the universe. From Selene, researchers monitor the deep harmonic structure of space, listening for patterns that the Earth-based arrays cannot resolve through atmospheric interference. What they hear is not always explicable. The data from Selene has raised more questions than it has answered.',
      },
      {
        name: 'Ares Reach',
        designation: 'H-14',
        body: 'Mars',
        population: '~8,500',
        function: 'Agricultural optimization and expansion logistics. A proving ground for living away from Earth entirely. Ares Reach tests the viability of closed-loop agricultural systems in reduced gravity, extreme temperature variance, and radiation conditions that Earth\'s Havens never experience.',
        visual: 'Dust-filter vestibules, pressure seals, domed greenhouses set against rust-red horizons. The Martian landscape is visible through observation ports — an alien expanse of oxide plains and ancient geological formations that dwarf the settlement. The greenhouses glow against the red terrain like emerald lanterns.',
        culture: 'Pragmatic frontier mindset without romance. Survival as daily practice. Everything takes effort, and the effort is the point. There is no nostalgia here because there is nothing to be nostalgic for — Ares Reach was built from nothing, on a world that has never supported life.',
        identity: 'The argument for expansion made physical. Ares Reach demonstrates that humanity can sustain itself beyond Earth. Every successful crop cycle, every child born on Martian soil, every system that runs without failure is a data point in an argument that will define the next century of human civilization.',
      },
    ],
  },

  coalition: {
    heading: 'The Coalition',
    lead: 'A cooperative system designed for stability. Stability is more fragile than it appears.',
    intro: 'The Global Coalition is the governing framework coordinating the Haven Network. Ratified in 2110, the Coalition Charter established a cooperative system designed to maintain stability across multiple biospheres through energy allocation, information coordination, and mobility permissions. It does not govern through armies or ideology. It governs through infrastructure. The Coalition exists because no single Haven can survive alone, and the systems that connect them require coordinated management.',
    structure: 'The Coalition operates through a Council of Havens, a representation framework providing public legitimacy while functional leverage determines real influence. Decisions affecting energy allocation require coordination with Haven Two and Haven Ten. Transit policy cannot be amended without Haven Seven\'s technical validation. Research classifications require sign-off from relevant specialist Havens. The system is designed to prevent unilateral action — and to ensure that the people closest to each critical system have authority over how it operates.',
    pillars: [
      {
        title: 'Energy Allocation',
        text: 'The Sahara Core fusion backbone powers every Haven membrane, every atmospheric cycle, every Traverse corridor. The Coalition manages distribution across a civilization-wide baseline: roughly seventy-eight percent to civilian infrastructure, fourteen percent to Traverse stabilization, and the remainder to research and missions. Energy allocation is not an economic abstraction. It is the real constitution of the Haven Network. When energy is redirected, outer ring districts feel it first: thinner air, longer transit queues, dimmer corridors.',
      },
      {
        title: 'Traverse Authorization',
        text: 'The Traverse network connects Havens through stabilized Fold corridors anchored at fixed nodes in harmonic space. Travel is scheduled in Universal Time windows and controlled through authorization tiers. Most civilians rarely travel between Havens. Transit capacity is finite, and access is a privilege. Passenger travel exists, but freight and critical personnel are prioritized. In a civilization where mobility is managed, controlling who moves and when is controlling the future.',
      },
      {
        title: 'Information Coordination',
        text: 'Research exchange, crisis response protocols, and public safety communications flow through Coalition channels. Universal Time, standardized in 2115, synchronizes operations across fourteen biospheres. The standardization was not universally welcomed — Haven Five resisted for months, arguing that cultural timekeeping was a form of identity that Universal Time erased. The Coalition maintained that synchronized operations were non-negotiable for a civilization sustained by interconnected systems.',
      },
      {
        title: 'Coalition Credits',
        text: 'The Haven economy runs on Coalition Credits, a currency pegged to Sahara Core energy output. Economic stability is directly coupled to fusion output. When the grid strains, the currency wobbles. When the currency wobbles, people notice. The system was designed to make economic health transparently dependent on infrastructure health — a reminder that prosperity in the Haven Network is not abstract. It is measured in watts.',
      },
    ],
  },

  phenomena: {
    heading: 'Known Phenomena',
    lead: 'The deeper humanity reaches, the less empty space becomes.',
    intro: 'During the early decades of Fold research and deep space probe deployment, instruments have detected patterns that do not conform to existing models. These observations remain under active study. What follows is drawn from publicly available research summaries. The phenomena documented here represent the boundary of human understanding — observations confirmed by multiple independent sources, yet unexplained by any existing theoretical framework.',
    entries: [
      {
        title: 'Harmonic Residuals',
        classification: 'Confirmed — Under Active Study',
        text: 'Fold transit corridors retain measurable harmonic traces after use. These residuals do not dissipate on expected timescales. Research teams have observed that repeated transit through the same corridor produces cumulative traces, as if the act of passage leaves a mark on the structure of space itself. The implications are still being modeled. If harmonic residuals compound indefinitely, every corridor is slowly changing the medium it travels through.',
      },
      {
        title: 'Probe Signal Anomalies',
        classification: 'Confirmed — Classification Pending',
        text: 'Two deep-range probes — the Kepler Array, launched in 2123, and the Asterion Beacon, launched in 2125 — transmitted data for brief windows before going silent. The Kepler Array returned seventeen minutes of density data. The Asterion Beacon, modified for a lower-emission signature, returned four minutes before cessation. The silence was not consistent with hardware failure. Subsequent analysis suggested the probes transitioned to a state that current instruments cannot resolve.',
      },
      {
        title: 'Resonance Correlation',
        classification: 'Under Review — Restricted Distribution',
        text: 'Signal analysts have identified patterns in background harmonic data that appear to correlate with human activity. The correlation is not yet understood as mechanism. The question is not whether the patterns exist, but whether they are responsive. If the harmonic structure of space reacts to human presence, the relationship between observer and medium is fundamentally different than current models assume.',
      },
      {
        title: 'Null Verge',
        classification: 'Confirmed — Permanent Exclusion Zone',
        text: 'A permanent dead zone exists where Traverse corridors cannot stabilize. It formed following an anchor failure and represents a region where accumulated harmonic strain has altered the local structure of space beyond recovery. It is the only confirmed evidence that human technology can permanently scar the fabric it travels through. The Null Verge is monitored continuously. It is not growing. It is not shrinking. It is simply there — a wound in the structure of space that does not heal.',
      },
      {
        title: 'Deep Harmonic Background',
        classification: 'Confirmed — Origin Unknown',
        text: 'Across all frequencies monitored by Haven Eight and Selene, a persistent low-level harmonic signal has been detected since instruments became sensitive enough to resolve it. The signal predates human Fold activity. It is not generated by any known natural phenomenon. It is everywhere, at every scale, at a frequency that sits just below the threshold of reliable analysis. Researchers describe it as structure that was always there, waiting to be heard.',
      },
    ],
  },

  contact: {
    heading: 'Transmit',
    subheading: 'Questions about the Haven Network. Requests for early access to archived material.',
    email: 'jordan@cosmicreachcreative.com',
    note: 'Responses are not guaranteed, but every transmission is received.',
    actions: [
      {
        label: 'Request Early Access',
        description: 'Receive new material from the Launch Window Zero universe as it becomes available.',
      },
      {
        label: 'Ask About the Universe',
        description: 'Questions about the Haven Network, the Coalition, or the world beyond the domes.',
      },
    ],
  },
};
